#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Customize to your needs...
bindkey '^r' history-incremental-search-backward
export KEYTIMEOUT=1
bindkey -v
export EDITOR='vim'
export VISUAL='vim'
bindkey -M vicmd v edit-command-line

export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

source ~/.pyenv/completions/pyenv.zsh
export PYTHONSTARTUP=~/.startup.py

alias mm="mux start default matt"

source ~/.bin/tmuxinator.zsh
